#!/bin/sh
##################################################################################
#
# Removes the contents of text blocks in an ABC file to avoid perturbation 
# in some conversions (for instance with abc2xml).
#
# This command is used as a filter from standard input to standard output.
#
# Frédéric Boulanger                     frederic.softdev@gmail.com
#
##################################################################################
if [ $# -gt 0 ]
then
  echo "# Usage: abcrmtext"
  echo "#        Filters out the contents of %%begintext/%%endtext blocks"
  echo "#        from standard input to standard output."
  exit 1
fi
gobbling=0
while IFS= read -r line
do
  if [[ "$line" =~ ^%%begintext ]]
  then
    gobbling=1
  elif [[ "$line" =~ ^%%endtext ]]
  then
    gobbling=0
  else
    if [ $gobbling == 0 ]
    then
	    echo "$line"
	  fi
  fi
done
